# Generated by Django 6.0.2 on 2026-02-07 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Package Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for package cards', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days')),
                ('duration_nights', models.PositiveIntegerField(help_text='Number of nights')),
                ('location', models.CharField(max_length=200)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_state', models.CharField(blank=True, max_length=100)),
                ('destination_country', models.CharField(default='India', max_length=100)),
                ('featured_image', models.ImageField(upload_to='packages/featured/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('inclusions', models.TextField(help_text="What's included (one per line)")),
                ('exclusions', models.TextField(help_text="What's not included (one per line)")),
                ('itinerary', models.TextField(help_text='Day-wise itinerary')),
                ('highlights', models.TextField(blank=True, help_text='Package highlights (one per line)')),
                ('activities', models.TextField(blank=True, help_text='Activities included (one per line)')),
                ('hotel_type', models.CharField(blank=True, help_text='e.g., 3-star, 4-star, Resort', max_length=100)),
                ('meal_plan', models.CharField(blank=True, help_text='e.g., Breakfast, All Meals', max_length=100)),
                ('transport_mode', models.CharField(blank=True, help_text='e.g., Flight, Train, Bus', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('max_people', models.PositiveIntegerField(default=10)),
                ('min_people', models.PositiveIntegerField(default=1)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('popular', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.packagecategory')),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='packages.package')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveIntegerField(help_text='Rating out of 5', validators=[django.core.validators.MinValueValidator(1)])),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
