# Generated by Django 6.0.2 on 2026-02-07 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_location', models.CharField(blank=True, help_text='City or Country', max_length=100)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('package_name', models.CharField(help_text='Which package they booked', max_length=200)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(help_text='Rating out of 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(help_text='Short headline for the review', max_length=200)),
                ('review', models.TextField(help_text='Detailed review')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/')),
                ('approved', models.BooleanField(default=False, help_text='Show on website')),
                ('featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
